# This file was *autogenerated* from the file storage/01a_polys/vert_in_facet.sage
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_27 = Integer(27); _sage_const_4 = Integer(4)
k=_sage_const_8 
a=_sage_const_4 
coord = [[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],[_sage_const_1 ,_sage_const_1 ,_sage_const_0 ],[a,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,a,_sage_const_0 ],[a,a,_sage_const_0 ],[_sage_const_1 ,a,_sage_const_0 ],[a,_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_1 ,_sage_const_1 ],[a,_sage_const_0 ,_sage_const_1 ],[_sage_const_0 ,a,_sage_const_1 ],[a,a,_sage_const_1 ],[_sage_const_1 ,a,_sage_const_1 ],[a,_sage_const_1 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_0 ,a],[_sage_const_1 ,_sage_const_0 ,a],[_sage_const_0 ,_sage_const_1 ,a],[_sage_const_1 ,_sage_const_1 ,a],[a,_sage_const_0 ,a],[_sage_const_0 ,a,a],[a,a,a],[_sage_const_1 ,a,a],[a,_sage_const_1 ,a]]
polys = []
with open('storage/01a_polys/014polys/act_vert'+str(k)+'.txt','r') as filer:
	for line in filer:
		vert_coord = eval(line)
		vert_in_facet = []
		for vert in vert_coord:
			for i in range(_sage_const_27 ):
				if vert == coord[i]:
					vert_in_facet.append(i)
		polys.append(vert_in_facet)		
with open('storage/01a_polys/014polys/act_vert'+str(k)+'.txt','w') as filew:
	for p in polys:		    
		filew.write(str(p))
		filew.write('\n')
